<a href="https://colab.research.google.com/github/HongSeongMo/Airbnb/blob/main/Copy_of_airbnb_lecture_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

7강. 매출예측 모델 검증

검증 데이터 읽기

In [ ]:
import pandas as pd

In [ ]:
# 검증 데이터 가져오기
path = 'drive/MyDrive/letuin/airbnb/data'

X_test = pd.read_csv(f'{path}/x_test.csv')
y_test = pd.read_csv(f'{path}/y_test.csv')

학습된 모델 가져오기

In [ ]:
import joblib

# path
path_model = 'drive/MyDrive/letuin/airbnb/model'

Linear Model

In [ ]:
# linear model
model_linear = joblib.load(f"{path_model}/model_linear.pkl")

In [ ]:
model_linear

LinearRegression()

Tree Model

In [ ]:
# tree model
model_tree = joblib.load(f"{path_model}/model_tree.pkl")

In [ ]:
model_tree

DecisionTreeRegressor(max_leaf_nodes=100)

Random Forest Regressor

*   싸이킷런 공식 문서 :

In [ ]:
# random forest model
model_rf = joblib.load(f"{path_model}/model_rf.pkl")

In [ ]:
model_rf

RandomForestRegressor(max_depth=5, max_leaf_nodes=30, random_state=1)

XGBoost Regressor
*   XGBoost 공식문서 :

In [ ]:
# xgboost model
model_xgb = joblib.load(f"{path_model}/model_xgb.pkl")

In [ ]:
model_xgb

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaf_nodes=30,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

모델 성능 비교

매출 예측

In [ ]:
X_test.head()

accommodates  availability_365  calculated_host_listings_count  \
0             2                 0                               1   
1             1                23                               1   
2             2               217                               4   
3             1               283                              30   
4             2                 0                               1   

   minimum_maximum_nights   latitude  number_of_reviews  \
0                  1125.0  51.577750                  1   
1                   365.0  51.517741                  0   
2                   365.0  51.548278                  0   
3                  1125.0  51.513060                 10   
4                  1125.0  51.448470                  0   

   maximum_minimum_nights  review_scores_value  review_scores_accuracy  \
0                     1.0             5.000000                5.000000   
1                    10.0             4.598477                4.715774   
2                     3.0             4.598477                4.715774   
3                     3.0             4.800000                4.800000   
4                     1.0             4.598477                4.715774   

   review_scores_location  ...  host_response_rate  host_acceptance_rate  \
0                5.000000  ...                 0.0                   0.0   
1                4.720782  ...               100.0                  75.0   
2                4.720782  ...               100.0                 100.0   
3                4.800000  ...               100.0                  99.0   
4                4.720782  ...                 0.0                   0.0   

   room_entire  room_hotel  room_private  room_shared  response_3d  \
0            1           0             0            0            0   
1            1           0             0            0            0   
2            0           0             1            0            0   
3            0           0             1            0            0   
4            0           0             1            0            0   

   response_1d  response_3h  response_1h  
0            0            0            0  
1            0            1            0  
2            0            0            1  
3            0            0            1  
4            0            0            0  

[5 rows x 52 columns]

In [ ]:
# Impute missing values in X_train
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
X_test = imputer.fit_transform(X_test)

In [ ]:
X_test = pd.DataFrame(X_test, columns=['accommodates', 'availability_365', 'calculated_host_listings_count',
       'minimum_maximum_nights', 'latitude', 'number_of_reviews',
       'maximum_minimum_nights', 'review_scores_value',
       'review_scores_accuracy', 'review_scores_location',
       'review_scores_checkin', 'host_listings_count', 'reviews_per_month',
       'review_scores_rating', 'maximum_nights_avg_ntm', 'maximum_nights',
       'minimum_nights', 'number_of_reviews_ltm', 'review_scores_cleanliness',
       'availability_30', 'host_total_listings_count',
       'review_scores_communication',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'minimum_nights_avg_ntm', 'availability_90', 'minimum_minimum_nights',
       'maximum_maximum_nights', 'longitude',
       'calculated_host_listings_count_shared_rooms', 'number_of_reviews_l30d',
       'availability_60', 'beds', 'host_is_superhost', 'host_has_profile_pic',
       'host_identity_verified', 'has_availability', 'instant_bookable',
       'host_since', 'last_review', 'first_review', 'price',
       'host_response_rate', 'host_acceptance_rate', 'room_entire',
       'room_hotel', 'room_private', 'room_shared', 'response_3d',
       'response_1d', 'response_3h', 'response_1h'])

In [ ]:
# predict by each model
y_pred_linear = model_linear.predict(X_test)
y_pred_tree = model_tree.predict(X_test)
y_pred_rf = model_rf.predict(X_test)
y_pred_xgb = model_xgb.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but DecisionTreeRegressor was fitted without feature names
  warnings.warn(


In [ ]:
y_pred_linear

array([[-394.35338618],
       [-426.86718792],
       [-546.75403991],
       ...,
       [-224.92168542],
       [-309.28055964],
       [2703.54025661]])

In [ ]:
y_pred_tree

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
y_pred_rf

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
y_pred_xgb

array([6.1331787e-07, 6.1331787e-07, 6.1331787e-07, ..., 6.1331787e-07,
       6.1331787e-07, 6.1331787e-07], dtype=float32)

array to dataframe

In [ ]:
import numpy as np

In [ ]:
np.hstack(y_pred_linear)

array([-394.35338618, -426.86718792, -546.75403991, ..., -224.92168542,
       -309.28055964, 2703.54025661])

In [ ]:
np.column_stack((np.hstack(y_pred_linear), y_pred_tree, y_pred_rf, y_pred_xgb))

array([[-3.94353386e+02,  0.00000000e+00,  0.00000000e+00,
         6.13317866e-07],
       [-4.26867188e+02,  0.00000000e+00,  0.00000000e+00,
         6.13317866e-07],
       [-5.46754040e+02,  0.00000000e+00,  0.00000000e+00,
         6.13317866e-07],
       ...,
       [-2.24921685e+02,  0.00000000e+00,  0.00000000e+00,
         6.13317866e-07],
       [-3.09280560e+02,  0.00000000e+00,  0.00000000e+00,
         6.13317866e-07],
       [ 2.70354026e+03,  0.00000000e+00,  0.00000000e+00,
         6.13317866e-07]])

In [ ]:
y_pred_df = pd.DataFrame(np.column_stack((np.hstack(y_pred_linear), y_pred_tree, y_pred_rf, y_pred_xgb)),
                         columns=['pred_linear', 'pred_tree', 'pred_rf', 'pred_xgb'])

y_pred_df.head()

pred_linear  pred_tree  pred_rf      pred_xgb
0  -394.353386        0.0      0.0  6.133179e-07
1  -426.867188        0.0      0.0  6.133179e-07
2  -546.754040        0.0      0.0  6.133179e-07
3  -310.600973        0.0      0.0  6.133179e-07
4   135.407750        0.0      0.0  6.133179e-07

실제 revenue 와 merge

In [ ]:
y_test

revenue
0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
...        ...
30282      0.0
30283      0.0
30284      0.0
30285      0.0
30286      0.0

[30287 rows x 1 columns]